git:
  submodules: false

# Enable C++ support
language: cpp

# Compiler selection
sudo: required
dist: trusty

addons:
  apt:
    sources:
      - llvm-toolchain-precise
      - ubuntu-toolchain-r-test

    packages:
      - g++-8
      - gcc-8

matrix:
  include:
    - env: BUILD_TYPE=Release
      os: linux
      compiler: clang

    - env: BUILD_TYPE=Release
      os: linux
      compiler: gcc-8

    - env: BUILD_TYPE=Release
      os: osx
      osx_image: xcode10
      compiler: clang

install:
  - |
    if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then
      if [ "$CXX" = "g++" ]; then export CXX="g++-8" CC="gcc-8"; fi
      sudo apt-get update -qq
      sudo bash ./scripts/ubuntu_deps.sh
    fi

script:
  - $CXX --version
  - mkdir build
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=${BUILD_TYPE} ..
  - make

