git:
  submodules: false

# permissions
sudo: false

# Enable C++ support
language: cpp

# Compiler selection
dist: bionic

addons:
  apt:
    packages:
      - cmake
      - ninja-build

matrix:
  include:
    - env: BUILD_TYPE=Release
      os: linux
      compiler: clang
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-xenial-9']
          packages: ['clang-9', 'clang++-9', 'lld-9', 'libc++-9-dev', 'libc++abi-9-dev', 'libboost-all-dev', 'libxmu-dev', 'libxi-dev', 'libsdl2-dev', 'liblua5.1-dev']
      env:
        - CC=clang-9
        - CXX=clang++-9

    - env: BUILD_TYPE=Release
      os: linux
      compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-xenial-9']
          packages: ['gcc-9', 'g++-9', 'libboost-all-dev', 'libxmu-dev', 'libxi-dev', 'libsdl2-dev', 'liblua5.1-dev']
      env:
        - CC=gcc-9
        - CXX=g++-9

    - env: BUILD_TYPE=Release
      os: osx
      osx_image: xcode11
      compiler: clang

script:
  - $CXX --version
  - mkdir build
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=${BUILD_TYPE} ..
  - cmake --build .
