git:
  submodules: false

# Enable C++ support
language: cpp

# Compiler selection
sudo: required
dist: bionic

matrix:
  include:
    - env: BUILD_TYPE=Release
      os: linux
      compiler: clang
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-xenial-9']
          packages: ['clang-9', 'clang++-9', 'lld-9']
      env:
        - CC=clang-9
        - CXX=clang++-9

    - env: BUILD_TYPE=Release
      os: linux
      compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-xenial-9']
          packages: ['gcc-9', 'g++-9']
      env:
        - CC=gcc-9
        - CXX=g++-9

    - env: BUILD_TYPE=Release
      os: osx
      osx_image: xcode11
      compiler: clang

install:
  - |
    if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then
      sudo apt-get update -qq
      sudo bash ./scripts/ubuntu_deps.sh
    fi

script:
  - $CXX --version
  - mkdir build
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=${BUILD_TYPE} ..
  - make

