# Specify version format
version: "{build}"

# Operating system (build VM template)
os: Visual Studio 2017

# build platform, i.e. Win32 (instead of x86), x64, Any CPU. This setting is optional.
platform:
  - Win32
  - x64

# build Configuration, i.e. Debug, Release, etc.
configuration:
#  - Debug
  - Release

# scripts that are called at very beginning, before repo cloning
init:
  - cmd: cmake --version
  - cmd: msbuild /version

# clone directory
clone_folder: C:\projects\cppzone

# scripts that run after cloning repository
install:
  - cmd: sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
  - cmd: git submodule update --init --recursive

# scripts to run before build
before_build:
  - cmd: cd C:\projects\cppzone
  - cmd: md build
  - cmd: cd build
  # We generate project files for Visual Studio 12 because the boost binaries installed on the test server are for Visual Studio 15.
  - cmd: if "%platform%"=="Win32" cmake -G "Visual Studio 15" -DCMAKE_BUILD_TYPE="%configuration%" ..
  - cmd: if "%platform%"=="x64"   cmake -G "Visual Studio 15 Win64" -DCMAKE_BUILD_TYPE="%configuration%" ..

build:
  project: C:\projects\cppzone\build\I++.sln
